# This workflow is automatically distributed from the following repository:
# https://github.com/legnoh/github-repo-configs/blob/main/modules/repo/templates/.github/workflows/automerge.yml.tftpl
name: Merge Dependencies

on: 
  pull_request_target:
    branches: [main]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.user.login == 'dependabot[bot]' ||
      github.event.pull_request.user.login == 'renovate[bot]' ||
      github.event.pull_request.user.login == 'legnoh-bump-bot[bot]'
    steps:
      - name: Create bump-bot Token
        id: github-app
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.G_BUMP_BOT_ID }}
          private-key: ${{ secrets.G_BUMP_BOT_PRIVATEKEY }}

      - name: Enable auto-merge on PR
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ steps.github-app.outputs.token }}

      - name: Approve PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ steps.github-app.outputs.token }}
